stages:
 - stage: Infrastructure
   jobs:
   - job: Check
     continueOnError: true
     steps:
     -  bash: exit 1
        name: InfraExists
   - job: Deploy
     dependsOn: Check
     condition: succeededOrFailed('Check')
     steps:
     -  bash: echo $(Check.InfraExists); exit 0;
 - stage: Kubernetes
   dependsOn: Infrastructure
   condition: succeededOrFailed('Infrastructure')
   jobs:
   - job: Check
     continueOnError: true
     steps:
     -  bash: exit 1
   - job: Deploy
     dependsOn: Check
     condition: failed('Check')
     steps:
     -  bash: exit 0