stages:
 - stage: Intrastructure
   jobs:
   - job: Check
     steps:
     -  bash: echo '##vso[task.setvariable variable=deploy;isOutput=true]true'
        name: validate
   - job: Deploy
     steps:
     -  bash: echo "Deploy"