stages:
 - stage: Infrastructure
   jobs:
   - job: Check
     continueOnError: true
     steps:
     -  bash: echo '##vso[task.setvariable variable=Exists;isOutput=true]true'; exit 1
        name: Infra
   - job: Deploy
     dependsOn: Check
     condition: eq(dependencies.Check.outputs['Infra.Exists'],true)
     steps:
     -  bash: echo "deploy"; exit 0;
 - stage: Kubernetes
   dependsOn: Infrastructure
   condition: succeededOrFailed('Infrastructure')
   jobs:
   - job: Check
     continueOnError: true
     steps:
     -  bash: echo '##vso[task.setvariable variable=Exists;isOutput=true]true'; exit 1
        name: Kubernetes
   - job: Deploy
     dependsOn: Check
     condition: eq(dependencies.Check.outputs['Kubernetes.Exists'],true)
     steps:
     -  bash: exit 0