stages:
 - stage: Intrastructure
   jobs:
   - job: Check
     steps:
     -  bash: echo '##vso[task.setvariable variable=deploy;isOutput=true]true'
        name: validate
   - job: Deploy
     dependsOn: Check
     condition: failed('Check')
     steps:
     -  bash: echo "Deploy"
 - stage: Kubernetes
   dependsOn: Infrastructure
   condition: succeeded('Intrastructure')
   jobs:
   - job: Check