stages:
 - stage: Infrastructure
   jobs:
   - job: Check
     continueOnError: true
     steps:
     -  bash: exit 1
        name: validate
   - job: Deploy
     dependsOn: Check
     condition: failed('Check')
     steps:
     -  bash: echo "Deploy"
 - stage: Kubernetes
   dependsOn: Infrastructure
   condition: succeeded('Infrastructure.Deploy')
   jobs:
   - job: Check